import Footer from "@/components/Footer/Footer";
import "@fortawesome/fontawesome-svg-core/styles.css";
import type { Metadata, Viewport } from "next";
import {
  Cedarville_Cursive,
  Geist,
  Geist_Mono,
  Inter,
  Roboto,
  Sunflower,
} from "next/font/google";
import "./globals.css";

const sunflower = Sunflower({
  weight: ["300", "500", "700"],
  variable: "--font-sunflower",
});
const cursive = Cedarville_Cursive({
  weight: ["400"],
  variable: "--font-cursive",
});
const inter = Inter({
  weight: ["300", "500", "700"],
  variable: "--font-inter",
});
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // maximumScale: 1, 
  // userScalable: false, 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${sunflower.variable} ${inter.variable} ${cursive.variable} ${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased overflow-x-hidden`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
