import "@fortawesome/fontawesome-svg-core/styles.css";
import type { Metadata } from "next";
import {
  Cedarville_Cursive,
  Geist,
  Geist_Mono,
  Inter,
  Roboto,
} from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import type { Viewport } from "next";
import { Sunflower } from "next/font/google";

const sunflower = Sunflower({
  weight: ["300", "500", "700"],
  variable: "--font-sunflower",
});
const cursive = Cedarville_Cursive({
  weight: ["400"],
  variable: "--font-cursive",
});
const inter = Inter({
  weight: ["300", "500", "700"],
  variable: "--font-inter",
});
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ✅ Fix 1: Use Next.js viewport export ONLY — remove the manual <meta> tag
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1, // 👈 ADD THIS — prevents mobile browsers from zooming/scaling wrong
  userScalable: false, // 👈 ADD THIS — locks the viewport on real devices
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* ✅ Fix 2: Remove the misplaced <meta> tag that was here */}
      <body
        className={`${sunflower.variable} ${inter.variable} ${cursive.variable} ${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased overflow-x-hidden`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
