export const RatesProviders = [
  {
    id: 1,
    name: "Sendwave",
    logo: "/send.png",
    abbr: "SE",
    rate: "₦7500",
    price: 7500,
  },
  {
    id: 2,
    name: "WorldRemit",
    logo: "/wr.png",
    abbr: "WO",
    rate: "₦7550",
    price: 7550,
  },
  {
    id: 3,
    name: "Lemfi",
    logo: "/lem.png",
    abbr: "LE",
    rate: "₦7520",
    price: 7520,
  },
  {
    id: 4,
    name: "Wise",
    logo: "/wise.png",
    abbr: "WI",
    rate: "₦7530",
    price: 7530,
  },
  {
    id: 5,
    name: "Remitly",
    logo: "/rem.png",
    abbr: "RE",
    rate: "₦7540",
    price: 7540,
  },
  {
    id: 6,
    name: "Sendwave",
    logo: "/send.png",
    abbr: "SE",
    rate: "₦7500",
    price: 6500,
  },
  {
    id: 7,
    name: "WorldRemit",
    logo: "/wr.png",
    abbr: "WO",
    rate: "₦7550",
    price: 5550,
  },
  {
    id: 8,
    name: "Lemfi",
    logo: "/lem.png",
    abbr: "LE",
    rate: "₦7520",
    price: 6520,
  },
  {
    id: 9,
    name: "Wise",
    logo: "/wise.png",
    abbr: "WI",
    rate: "₦7530",
    price: 5530,
  },
  {
    id: 10,
    name: "Remitly",
    logo: "/rem.png",
    abbr: "RE",
    rate: "₦7540",
    price: 4540,
  },
  {
    id: 11,
    name: "Sendwave",
    logo: "/send.png",
    abbr: "SE",
    rate: "₦7500",
    price: 5500,
  },
  {
    id: 12,
    name: "WorldRemit",
    logo: "/wr.png",
    abbr: "WO",
    rate: "₦7550",
    price: 2550,
  },
  {
    id: 13,
    name: "Lemfi",
    logo: "/lem.png",
    abbr: "LE",
    rate: "₦7520",
    price: 6520,
  },
  {
    id: 14,
    name: "Wise",
    logo: "/wise.png",
    abbr: "WI",
    rate: "₦7530",
    price: 5530,
  },
  {
    id: 15,
    name: "Remitly",
    logo: "/rem.png",
    abbr: "RE",
    rate: "₦7540",
    price: 4540,
  },
  {
    id: 16,
    name: "Sendwave",
    logo: "/send.png",
    abbr: "SE",
    rate: "₦7500",
    price: 5500,
  },
  {
    id: 17,
    name: "WorldRemit",
    logo: "/wr.png",
    abbr: "WO",
    rate: "₦7550",
    price: 3550,
  },
  {
    id: 18,
    name: "Lemfi",
    logo: "/lem.png",
    abbr: "LE",
    rate: "₦7520",
    price: 5520,
  },
  {
    id: 19,
    name: "Wise",
    logo: "/wise.png",
    abbr: "WI",
    rate: "₦7530",
    price: 4530,
  },
  {
    id: 20,
    name: "Remitly",
    logo: "/rem.png",
    abbr: "RE",
    rate: "₦7540",
    price: 6540,
  },
];

export const Currencies = [
  {
    code: "AED",
    name: "United Arab Emirates Dirham",
    symbol: "د.إ",
    flag: "https://flagcdn.com/ae.svg",
  },
  {
    code: "AFN",
    name: "Afghan Afghani",
    symbol: "؋",
    flag: "https://flagcdn.com/af.svg",
  },
  {
    code: "ALL",
    name: "Albanian Lek",
    symbol: "L",
    flag: "https://flagcdn.com/al.svg",
  },
  {
    code: "AMD",
    name: "Armenian Dram",
    symbol: "֏",
    flag: "https://flagcdn.com/am.svg",
  },
  {
    code: "AOA",
    name: "Angolan Kwanza",
    symbol: "Kz",
    flag: "https://flagcdn.com/ao.svg",
  },
  {
    code: "ARS",
    name: "Argentine Peso",
    symbol: "$",
    flag: "https://flagcdn.com/ar.svg",
  },
  {
    code: "AUD",
    name: "Australian Dollar",
    symbol: "A$",
    flag: "https://flagcdn.com/au.svg",
  },
  {
    code: "AWG",
    name: "Aruban Florin",
    symbol: "ƒ",
    flag: "https://flagcdn.com/aw.svg",
  },
  {
    code: "AZN",
    name: "Azerbaijani Manat",
    symbol: "₼",
    flag: "https://flagcdn.com/az.svg",
  },
  {
    code: "BBD",
    name: "Barbadian Dollar",
    symbol: "Bds$",
    flag: "https://flagcdn.com/bb.svg",
  },
  {
    code: "BDT",
    name: "Bangladeshi Taka",
    symbol: "৳",
    flag: "https://flagcdn.com/bd.svg",
  },
  {
    code: "BGN",
    name: "Bulgarian Lev",
    symbol: "лв",
    flag: "https://flagcdn.com/bg.svg",
  },
  {
    code: "BHD",
    name: "Bahraini Dinar",
    symbol: ".د.ب",
    flag: "https://flagcdn.com/bh.svg",
  },
  {
    code: "BIF",
    name: "Burundian Franc",
    symbol: "FBu",
    flag: "https://flagcdn.com/bi.svg",
  },
  {
    code: "BMD",
    name: "Bermudian Dollar",
    symbol: "$",
    flag: "https://flagcdn.com/bm.svg",
  },
  {
    code: "BND",
    name: "Brunei Dollar",
    symbol: "$",
    flag: "https://flagcdn.com/bn.svg",
  },
  {
    code: "BOB",
    name: "Bolivian Boliviano",
    symbol: "Bs.",
    flag: "https://flagcdn.com/bo.svg",
  },
  {
    code: "BRL",
    name: "Brazilian Real",
    symbol: "R$",
    flag: "https://flagcdn.com/br.svg",
  },
  {
    code: "BSD",
    name: "Bahamian Dollar",
    symbol: "B$",
    flag: "https://flagcdn.com/bs.svg",
  },
  {
    code: "BTN",
    name: "Bhutanese Ngultrum",
    symbol: "Nu.",
    flag: "https://flagcdn.com/bt.svg",
  },
  {
    code: "BWP",
    name: "Botswana Pula",
    symbol: "P",
    flag: "https://flagcdn.com/bw.svg",
  },
  {
    code: "BYN",
    name: "Belarusian Ruble",
    symbol: "Br",
    flag: "https://flagcdn.com/by.svg",
  },
  {
    code: "BZD",
    name: "Belize Dollar",
    symbol: "BZ$",
    flag: "https://flagcdn.com/bz.svg",
  },
  {
    code: "CAD",
    name: "Canadian Dollar",
    symbol: "C$",
    flag: "https://flagcdn.com/ca.svg",
  },
  {
    code: "CDF",
    name: "Congolese Franc",
    symbol: "FC",
    flag: "https://flagcdn.com/cd.svg",
  },
  {
    code: "CHF",
    name: "Swiss Franc",
    symbol: "CHF",
    flag: "https://flagcdn.com/ch.svg",
  },
  {
    code: "CLP",
    name: "Chilean Peso",
    symbol: "$",
    flag: "https://flagcdn.com/cl.svg",
  },
  {
    code: "CNY",
    name: "Chinese Yuan",
    symbol: "¥",
    flag: "https://flagcdn.com/cn.svg",
  },
  {
    code: "COP",
    name: "Colombian Peso",
    symbol: "$",
    flag: "https://flagcdn.com/co.svg",
  },
  {
    code: "CRC",
    name: "Costa Rican Colón",
    symbol: "₡",
    flag: "https://flagcdn.com/cr.svg",
  },
  {
    code: "CUP",
    name: "Cuban Peso",
    symbol: "$",
    flag: "https://flagcdn.com/cu.svg",
  },
  {
    code: "CZK",
    name: "Czech Koruna",
    symbol: "Kč",
    flag: "https://flagcdn.com/cz.svg",
  },
  {
    code: "DJF",
    name: "Djiboutian Franc",
    symbol: "Fdj",
    flag: "https://flagcdn.com/dj.svg",
  },
  {
    code: "DKK",
    name: "Danish Krone",
    symbol: "kr",
    flag: "https://flagcdn.com/dk.svg",
  },
  {
    code: "DOP",
    name: "Dominican Peso",
    symbol: "$",
    flag: "https://flagcdn.com/do.svg",
  },
  {
    code: "EGP",
    name: "Egyptian Pound",
    symbol: "£",
    flag: "https://flagcdn.com/eg.svg",
  },
  {
    code: "ETB",
    name: "Ethiopian Birr",
    symbol: "Br",
    flag: "https://flagcdn.com/et.svg",
  },
  {
    code: "EUR",
    name: "Euro",
    symbol: "€",
    flag: "https://flagcdn.com/eu.svg",
  },
  {
    code: "FJD",
    name: "Fijian Dollar",
    symbol: "FJ$",
    flag: "https://flagcdn.com/fj.svg",
  },
  {
    code: "GBP",
    name: "Pound Sterling",
    symbol: "£",
    flag: "https://flagcdn.com/gb.svg",
  },
  {
    code: "GEL",
    name: "Georgian Lari",
    symbol: "₾",
    flag: "https://flagcdn.com/ge.svg",
  },
  {
    code: "GHS",
    name: "Ghanaian Cedi",
    symbol: "₵",
    flag: "https://flagcdn.com/gh.svg",
  },
  {
    code: "GMD",
    name: "Gambian Dalasi",
    symbol: "D",
    flag: "https://flagcdn.com/gm.svg",
  },
  {
    code: "GTQ",
    name: "Guatemalan Quetzal",
    symbol: "Q",
    flag: "https://flagcdn.com/gt.svg",
  },
  {
    code: "GYD",
    name: "Guyanese Dollar",
    symbol: "$",
    flag: "https://flagcdn.com/gy.svg",
  },
  {
    code: "HKD",
    name: "Hong Kong Dollar",
    symbol: "HK$",
    flag: "https://flagcdn.com/hk.svg",
  },
  {
    code: "HNL",
    name: "Honduran Lempira",
    symbol: "L",
    flag: "https://flagcdn.com/hn.svg",
  },
  {
    code: "HRK",
    name: "Croatian Kuna",
    symbol: "kn",
    flag: "https://flagcdn.com/hr.svg",
  },
  {
    code: "HTG",
    name: "Haitian Gourde",
    symbol: "G",
    flag: "https://flagcdn.com/ht.svg",
  },
  {
    code: "HUF",
    name: "Hungarian Forint",
    symbol: "Ft",
    flag: "https://flagcdn.com/hu.svg",
  },
  {
    code: "IDR",
    name: "Indonesian Rupiah",
    symbol: "Rp",
    flag: "https://flagcdn.com/id.svg",
  },
  {
    code: "ILS",
    name: "Israeli New Shekel",
    symbol: "₪",
    flag: "https://flagcdn.com/il.svg",
  },
  {
    code: "INR",
    name: "Indian Rupee",
    symbol: "₹",
    flag: "https://flagcdn.com/in.svg",
  },
  {
    code: "IQD",
    name: "Iraqi Dinar",
    symbol: "ع.د",
    flag: "https://flagcdn.com/iq.svg",
  },
  {
    code: "ISK",
    name: "Icelandic Króna",
    symbol: "kr",
    flag: "https://flagcdn.com/is.svg",
  },
  {
    code: "JMD",
    name: "Jamaican Dollar",
    symbol: "J$",
    flag: "https://flagcdn.com/jm.svg",
  },
  {
    code: "JPY",
    name: "Japanese Yen",
    symbol: "¥",
    flag: "https://flagcdn.com/jp.svg",
  },
  {
    code: "KES",
    name: "Kenyan Shilling",
    symbol: "KSh",
    flag: "https://flagcdn.com/ke.svg",
  },
  {
    code: "KRW",
    name: "South Korean Won",
    symbol: "₩",
    flag: "https://flagcdn.com/kr.svg",
  },
  {
    code: "KWD",
    name: "Kuwaiti Dinar",
    symbol: "د.ك",
    flag: "https://flagcdn.com/kw.svg",
  },
  {
    code: "LAK",
    name: "Lao Kip",
    symbol: "₭",
    flag: "https://flagcdn.com/la.svg",
  },
  {
    code: "LKR",
    name: "Sri Lankan Rupee",
    symbol: "Rs",
    flag: "https://flagcdn.com/lk.svg",
  },
  {
    code: "LSL",
    name: "Lesotho Loti",
    symbol: "L",
    flag: "https://flagcdn.com/ls.svg",
  },
  {
    code: "MAD",
    name: "Moroccan Dirham",
    symbol: "د.م.",
    flag: "https://flagcdn.com/ma.svg",
  },
  {
    code: "MXN",
    name: "Mexican Peso",
    symbol: "$",
    flag: "https://flagcdn.com/mx.svg",
  },
  {
    code: "MYR",
    name: "Malaysian Ringgit",
    symbol: "RM",
    flag: "https://flagcdn.com/my.svg",
  },
  {
    code: "NGN",
    name: "Nigerian Naira",
    symbol: "₦",
    flag: "https://flagcdn.com/ng.svg",
  },
  {
    code: "NOK",
    name: "Norwegian Krone",
    symbol: "kr",
    flag: "https://flagcdn.com/no.svg",
  },
  {
    code: "NZD",
    name: "New Zealand Dollar",
    symbol: "NZ$",
    flag: "https://flagcdn.com/nz.svg",
  },
  {
    code: "PEN",
    name: "Peruvian Sol",
    symbol: "S/",
    flag: "https://flagcdn.com/pe.svg",
  },
  {
    code: "PHP",
    name: "Philippine Peso",
    symbol: "₱",
    flag: "https://flagcdn.com/ph.svg",
  },
  {
    code: "PKR",
    name: "Pakistani Rupee",
    symbol: "Rs",
    flag: "https://flagcdn.com/pk.svg",
  },
  {
    code: "QAR",
    name: "Qatari Riyal",
    symbol: "ر.ق",
    flag: "https://flagcdn.com/qa.svg",
  },
  {
    code: "RUB",
    name: "Russian Ruble",
    symbol: "₽",
    flag: "https://flagcdn.com/ru.svg",
  },
  {
    code: "SAR",
    name: "Saudi Riyal",
    symbol: "ر.س",
    flag: "https://flagcdn.com/sa.svg",
  },
  {
    code: "SEK",
    name: "Swedish Krona",
    symbol: "kr",
    flag: "https://flagcdn.com/se.svg",
  },
  {
    code: "SGD",
    name: "Singapore Dollar",
    symbol: "S$",
    flag: "https://flagcdn.com/sg.svg",
  },
  {
    code: "THB",
    name: "Thai Baht",
    symbol: "฿",
    flag: "https://flagcdn.com/th.svg",
  },
  {
    code: "TND",
    name: "Tunisian Dinar",
    symbol: "د.ت",
    flag: "https://flagcdn.com/tn.svg",
  },
  {
    code: "TRY",
    name: "Turkish Lira",
    symbol: "₺",
    flag: "https://flagcdn.com/tr.svg",
  },
  {
    code: "TTD",
    name: "Trinidad & Tobago Dollar",
    symbol: "TT$",
    flag: "https://flagcdn.com/tt.svg",
  },
  {
    code: "TWD",
    name: "New Taiwan Dollar",
    symbol: "NT$",
    flag: "https://flagcdn.com/tw.svg",
  },
  {
    code: "UGX",
    name: "Ugandan Shilling",
    symbol: "USh",
    flag: "https://flagcdn.com/ug.svg",
  },
  {
    code: "USD",
    name: "US Dollar",
    symbol: "$",
    flag: "https://flagcdn.com/us.svg",
  },
  {
    code: "UYU",
    name: "Uruguayan Peso",
    symbol: "$U",
    flag: "https://flagcdn.com/uy.svg",
  },
  {
    code: "VES",
    name: "Venezuelan Bolívar",
    symbol: "Bs.",
    flag: "https://flagcdn.com/ve.svg",
  },
  {
    code: "VND",
    name: "Vietnamese Dong",
    symbol: "₫",
    flag: "https://flagcdn.com/vn.svg",
  },
  {
    code: "ZAR",
    name: "South African Rand",
    symbol: "R",
    flag: "https://flagcdn.com/za.svg",
  },
  {
    code: "ZMW",
    name: "Zambian Kwacha",
    symbol: "ZK",
    flag: "https://flagcdn.com/zm.svg",
  },
];
